version: '3.3'
services:
  db:
    image: mysql:5.7.28
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'developer'
      MYSQL_PASSWORD: 'changeit'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    command: mysqld --default-authentication-plugin=mysql_native_password --innodb_flush_neighbors=0
    ports:
      # Port Expose : MySQL Port running inside container
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where data will be persisted
    volumes:
      -my-db:/var/lib/mysql
# Names volume
volumes:
  my-db:
